/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/AboutModal/AboutModal.vue')['default']
    BatchRename: typeof import('./src/components/Toolbox/tools/BatchRename.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/ContextMenu.vue')['default']
    DeleteTab: typeof import('./src/components/Toolbox/tools/BatchRename/DeleteTab.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileDiff: typeof import('./src/components/Toolbox/tools/FileDiff.vue')['default']
    FileEncrypt: typeof import('./src/components/Toolbox/tools/FileEncrypt.vue')['default']
    FileGallery: typeof import('./src/components/FileGallery/FileGallery.vue')['default']
    FileToolbox: typeof import('./src/components/Toolbox/FileToolbox.vue')['default']
    FileTree: typeof import('./src/components/Toolbox/tools/FileTree.vue')['default']
    FormatConvert: typeof import('./src/components/Toolbox/tools/FormatConvert.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InsertTab: typeof import('./src/components/Toolbox/tools/BatchRename/InsertTab.vue')['default']
    LocalSearch: typeof import('./src/components/Toolbox/tools/LocalSearch.vue')['default']
    NumberingTab: typeof import('./src/components/Toolbox/tools/BatchRename/NumberingTab.vue')['default']
    PasswordConfig: typeof import('./src/components/PasswordConfig/PasswordConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDir: typeof import('./src/components/SelectDir/SelectDir.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal/SettingsModal.vue')['default']
    ShareFile: typeof import('./src/components/ShareFile/ShareFile.vue')['default']
    StorageConfigModal: typeof import('./src/components/StorageConfigModal/StorageConfigModal.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/UploadFile.vue')['default']
  }
}
